### PR TITLE
Include  yaml+toml data files in MANIFEST.in and remove setup.py

### PR DESCRIPTION
**Pull request by ianmkenney**
YAML files in the `dataset` module were not included in the installation. Including them as an entry in the MANIFEST.in fixes this.

### CODE REVIEW

**Comment by chrisiacovella** [comment]
These are included  in setup.py so they show up in the install.  Is the reason they need to be a manifest As well?

**Comment by ianmkenney** [comment]
I was going based on comments from @wiederm and my local install not showing them in my environment. I think I wasn't seeing them because of an editable installation. The [data files support docs](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) indicates you still need it though, so I'm a little unsure of what the absolute requirements are. It might be more important for `pyproject.toml` based builds.

**Comment by ianmkenney** [comment]
`setuptools` pulls information from the `pyproject.toml`. So the `setup.py`, in its current form, isn't needed. If we ever have a more complicated build process that cannot be expressed in the `pyproject.toml` then it may be needed again. For the simple use of including data files, `pyproject.toml` + `MANIFEST.in` will do.

**Review by chrisiacovella — APPROVED** [review]
thanks for making this change!

**Pull request merged**
